export const womenLedStocks = [
  { symbol: 'ELV', name: 'Elevance Health', leader: 'Gail Boudreaux', sector: 'Health care' },
  { symbol: 'CNC', name: 'Centene', leader: 'Sarah London', sector: 'Health care' },
  { symbol: 'GM', name: 'General Motors', leader: 'Mary Barra', sector: 'Auto' },
  { symbol: 'C', name: 'Citigroup', leader: 'Jane Fraser', sector: 'Financials' },
  { symbol: 'MPC', name: 'Marathon Petroleum', leader: 'Maryann Mannen', sector: 'Energy' },
  { symbol: 'UPS', name: 'United Parcel Service', leader: 'Carol Tome', sector: 'Logistics' },
  { symbol: 'PGR', name: 'Progressive', leader: 'Tricia Griffith', sector: 'Insurance' },
  { symbol: 'ORCL', name: 'Oracle', leader: 'Safra Catz', sector: 'Technology' },
  { symbol: 'BBY', name: 'Best Buy', leader: 'Corie Barry', sector: 'Retail' },
  { symbol: 'GD', name: 'General Dynamics', leader: 'Phebe Novakovic', sector: 'Defense' },
  { symbol: 'NOC', name: 'Northrop Grumman', leader: 'Kathy Warden', sector: 'Defense' },
  { symbol: 'CMI', name: 'Cummins', leader: 'Jennifer Rumsey', sector: 'Industrials' },
  { symbol: 'DUK', name: 'Duke Energy', leader: 'Lynn Good', sector: 'Utilities' },
  { symbol: 'OXY', name: 'Occidental Petroleum', leader: 'Vicki Hollub', sector: 'Energy' },
  { symbol: 'PCG', name: 'PG&E', leader: 'Patti Poppe', sector: 'Utilities' },
  { symbol: 'SHW', name: 'Sherwin-Williams', leader: 'Heidi Petz', sector: 'Materials' },
  { symbol: 'AMD', name: 'Advanced Micro Devices', leader: 'Lisa Su', sector: 'Semiconductors' },
  { symbol: 'CDW', name: 'CDW', leader: 'Christine Leahy', sector: 'Technology' },
  { symbol: 'ROST', name: 'Ross Stores', leader: 'Barbara Rentler', sector: 'Retail' },
  { symbol: 'PH', name: 'Parker-Hannifin', leader: 'Jennifer Parmentier', sector: 'Industrials' },
  { symbol: 'ADP', name: 'Automatic Data Processing', leader: 'Maria Black', sector: 'Software' },
  { symbol: 'KMI', name: 'Kinder Morgan', leader: 'Kim Dang', sector: 'Energy' },
  { symbol: 'ACN', name: 'Accenture', leader: 'Julie Sweet', sector: 'Consulting' },
  { symbol: 'FIS', name: 'Fidelity National Information Services', leader: 'Stephanie Ferris', sector: 'Fintech' },
  { symbol: 'LUMN', name: 'Lumen Technologies', leader: 'Kate Johnson', sector: 'Telecom' },
  { symbol: 'OTIS', name: 'Otis Worldwide', leader: 'Judith Marks', sector: 'Industrials' },
  { symbol: 'DKS', name: "Dick's Sporting Goods", leader: 'Lauren Hobart', sector: 'Retail' },
  { symbol: 'EXPE', name: 'Expedia Group', leader: 'Ariane Gorin', sector: 'Travel' },
  { symbol: 'DD', name: 'DuPont', leader: 'Lori Koch', sector: 'Materials' },
  { symbol: 'LNC', name: 'Lincoln National', leader: 'Ellen Cooper', sector: 'Insurance' },
  { symbol: 'HSY', name: 'Hershey', leader: 'Michele Buck', sector: 'Consumer' },
  { symbol: 'YUMC', name: 'Yum China', leader: 'Joey Wat', sector: 'Restaurants' },
  { symbol: 'ULTA', name: 'Ulta Beauty', leader: 'Kecia Steelman', sector: 'Retail' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', leader: 'Reshma Kewalramani', sector: 'Biotech' },
  { symbol: 'JBLU', name: 'JetBlue Airways', leader: 'Joanna Geraghty', sector: 'Airlines' },
  { symbol: 'NSIT', name: 'Insight Enterprises', leader: 'Joyce Mullen', sector: 'Technology' },
  { symbol: 'ZTS', name: 'Zoetis', leader: 'Kristin Peck', sector: 'Health care' },
  { symbol: 'EQIX', name: 'Equinix', leader: 'Adaire Fox-Martin', sector: 'Data centers' },
  { symbol: 'FL', name: 'Foot Locker', leader: 'Mary Dillon', sector: 'Retail' },
  { symbol: 'BEN', name: 'Franklin Resources', leader: 'Jenny Johnson', sector: 'Asset management' },
  { symbol: 'WSM', name: 'Williams-Sonoma', leader: 'Laura Alber', sector: 'Retail' },
  { symbol: 'SAIC', name: 'Science Applications International', leader: 'Toni Townes-Whitley', sector: 'Technology' },
  { symbol: 'BBWI', name: 'Bath & Body Works', leader: 'Gina Boswell', sector: 'Retail' },
  { symbol: 'TMHC', name: 'Taylor Morrison Home', leader: 'Sheryl Palmer', sector: 'Homebuilding' },
  { symbol: 'CLX', name: 'Clorox', leader: 'Linda Rendle', sector: 'Consumer' },
  { symbol: 'VOYA', name: 'Voya Financial', leader: 'Heather Lavallee', sector: 'Financials' },
  { symbol: 'DTE', name: 'DTE Energy', leader: 'Joi Harris', sector: 'Utilities' },
  { symbol: 'NEM', name: 'Newmont', leader: 'Natascha Viljoen', sector: 'Mining' },
  { symbol: 'TXT', name: 'Textron', leader: 'Lisa Atherton', sector: 'Industrials' },
  { symbol: 'MUSA', name: 'Murphy USA', leader: 'Mindy West', sector: 'Retail energy' },
]
